# Generated by Django 5.0.7 on 2024-09-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akasa', '0005_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
    ]
